import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import theme from "../theme";
import "./globals.css";
import { Footer, Header } from "./components";
import { Box, Divider } from "@mui/material";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Box
              display="flex"
              flexDirection="column"
              minHeight="100vh"
              position="relative"
            >
              <Header />
              {children}
              <Footer sx={{ mt: "auto" }} />
              <Divider
                orientation="vertical"
                sx={{
                  position: "absolute",
                  top: 0,
                  bottom: 0,
                  left: "35%",
                  zIndex: -1,
                }}
              />
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
